name: Build and deploy Node.js app to Azure Web App - gestor-tareas-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Debug - Show workspace structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Finding package.json files:"
          find . -name "package.json"

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          # Use the correct path based on repository structure
          if [ -f "./backend/package.json" ]; then
            cd backend
            echo "Found package.json in backend directory"
          elif [ -f "./package.json" ]; then
            echo "Found package.json in root directory"
          else
            echo "ERROR: package.json not found"
            exit 1
          fi
          
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Prepare artifact for deployment
        run: |
          # Create zip from the right location
          if [ -d "./backend" ]; then
            echo "Zipping from backend directory"
            cd backend
            zip -r ../release.zip ./*
          else
            echo "Zipping from current directory"
            zip -r release.zip ./*
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    # El resto del workflow permanece igual...