# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gestor-tareas-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Debug - List directory structure
        run: |
          pwd
          ls -la
          find . -type f -name "package.json"
          
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Cambiado a la versión 18.x por compatibilidad

      - name: Install dependencies
        run: |
          # Usar la ruta exacta al package.json según lo que encuentre el paso anterior
          if [ -f "./backend/package.json" ]; then
            cd backend
            npm install
          elif [ -f "./package.json" ]; then
            npm install
          else
            echo "No se encontró package.json"
            exit 1
          fi

      - name: npm run build
        run: |
          cd backend
          npm run build --if-present

      - name: npm run test
        run: |
          cd backend
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D52B51BF75824AFA87F9668030627F65 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EDFC41F8E98F43D7900E8088DAA9C383 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14133AF1745742A1ABCA930838671795 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gestor-tareas-api'
          slot-name: 'Production'
          package: .
