# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy API to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Navigate to backend and install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Build backend
      working-directory: ./backend
      run: npm run build --if-present

    - name: Test backend
      working-directory: ./backend
      run: npm test --if-present
      continue-on-error: true

    - name: Zip backend artifact
      run: |
        cd backend
        zip -r ../backend-deploy.zip ./*
        cd ..
        echo "Verificando contenido del ZIP:"
        unzip -l backend-deploy.zip | head -10

    - name: Upload backend artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-app
        path: backend-deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: backend-app

    - name: Unzip artifact
      run: |
        unzip backend-deploy.zip
        ls -la

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gestor-tareas-api'
        slot-name: 'Production'
        package: .

  azure_login:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  set_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        echo "ARM_CLIENT_ID=<GUID>" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=<STRING>" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=<GUID>" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=<GUID>" >> $GITHUB_ENV
